#!/bin/sh

# Run the script and get the return code if successful of if fails
a=$($1)
echo "a : $a"
./scripts/commit-message-check.sh $a && rc=$? || rc=$?
echo "return code : $rc"
if [ $rc -eq 1 ]
then
	echo "Script return code 1 so commit failed"
	exit 1
else
	echo "No error returned so commit successful"
fi
